// Ship the locked browser bundle so Git URL installations need no npm/build step.
import { build } from 'esbuild';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
const root = fileURLToPath(new URL('../', import.meta.url));
const pkg = JSON.parse(await readFile(new URL('../package.json', import.meta.url)));
const version = pkg.dependencies['@functional-systems/lambdadb'];
const result = await build({
    absWorkingDir: root,
    stdin: { contents: 'export { LambdaDBClient } from "@functional-systems/lambdadb/client"; export { HTTPClient } from "@functional-systems/lambdadb/lib/http";', resolveDir: root },
    bundle: true, write: false, format: 'esm', platform: 'browser', target: 'es2022',
    minify: true, legalComments: 'eof', charset: 'utf8',
    banner: { js: `// Generated by npm run build:sdk. LambdaDB SDK ${version}; see vendor/LICENSES.txt. Do not edit.` },
});
const licenses = await Promise.all(['@functional-systems/lambdadb', 'zod'].map(async name =>
    `${name}\n${await readFile(new URL(`../node_modules/${name}/LICENSE`, import.meta.url), 'utf8')}`));
const files = { 'lambdadb.js': result.outputFiles[0].text, 'LICENSES.txt': licenses.join('\n\n') + '\n' };
await mkdir(new URL('../vendor/', import.meta.url), { recursive: true });
for (const [name, content] of Object.entries(files)) {
    const target = new URL(`../vendor/${name}`, import.meta.url);
    if (process.argv.includes('--check')) assert.equal(await readFile(target, 'utf8'), content, `Stale SDK artifact: ${name}; run npm run build:sdk`);
    else await writeFile(target, content);
}
console.log(`SDK ${version}: ${Buffer.byteLength(files['lambdadb.js'])} bytes; ${process.argv.includes('--check') ? 'verified' : 'built'}`);
